name: 'Github onboarding Workflow'
on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Platform for which you want to add secret'
        required: true
      team_name:
        description: 'team name'
        required: true
      env:
        description: 'Enviornment '
        required: false
        default: ""
      aws_account:
        description: 'AWS Account'
        required: false
        default: ""
    
# Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash
  
jobs:  
  github-onboarding:
    name: 'Github onboarding job'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run github script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TEAM_NAME: ${{ secrets.SONAR_TEAM_NAME }}
        AWS_TOKEN: ${{ secrets.AWS_TOKEN }}
        PRISMA_TOKEN: ${{ secrets.PRISMA_TOKEN }}
        
      run: |
        python secrets_adds.py ${{ github.event.inputs.tool }} ${{ github.event.inputs.team_name }} ${{ github.event.inputs.env }} ${{ github.event.inputs.aws_account }}


